[package]
name = "awakesl/instinct"
description = "Creatures that learn what their senses predict, what their acts do, and what to do about it."
version = "0.5.5"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["mind", "mind/**", "default.project.json", "wally.toml", "README.md", "LICENSE"]
